services:
  mysql:
    image: mysql:9
    container_name: mysql
    env_file: ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    configs:
      - source: mysql_init
        target: /docker-entrypoint-initdb.d
      - source: mysql_config
        target: /etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  patient-service:
    image: patient-service
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - 3001:3000
    env_file: ./patient-service/.env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

configs:
  mysql_init:
    file: ./database/init
  mysql_config:
    file: ./database/config/my.cnf
